
version: 2.1
jobs:
  build:
    docker: 
      - image: franck44/linux-dafny # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: ls -al
      - run: echo "hello world" # run the `echo` command
      - run: python3 scripts/runTests.py "test"
      - run:
          name: run tests
          command: |
            mkdir test-results
            py.test scripts/pytesttests.py --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results   
      # - run: 
      #     command: |
      #      py.test scripts/pytesttests.py --junitxml=/tmp/test-results
      # - store_test_results:
      #     path: /tmp/test-results
      # - store_artifacts:
      #     path: test-results
      #     destination: tr1

